name: Curl with Cloudflare Headers

on:
  workflow_dispatch: # Allows manual triggering
  # You can also add other triggers like:
  # push:
  #   branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"

env:
  TARGET: "https://unraid.kagno.com"
  CF_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
  CF_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  UTK: ${{ secrets.utk }}

jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Curl request with verbose output (optional)
        run: |
          curl -L -X GET \
            -H "utk: ${{env.UTK}}" \
            -H "CF-Access-Client-Id: ${{env.CF_ID}}" \
            -H "CF-Access-Client-Secret: ${{env.CF_SECRET}}" \
            -w "\nResponse Code: %{http_code}\n" \
            "${{env.TARGET}}"
